name: CI

# on: [push]
on:
  push:
    branches:
      - main
  workflow_dispatch: # Put here!!
  schedule:
  - cron: "*/8 * * * *" # run every 8 minutes
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v1
    # - name: Run a one-line script
    #   run: echo Hello, world!
    # - name: Run a multi-line script
    #   run: |
    #     echo Add oher actions to build,
    #     echo test, and deploy your project.
    - uses: actions/checkout@v1
    - uses: julia-actions/setup-julia@v1
      with:
          version: '1.8.1'
    - uses: julia-actions/julia-buildpkg@master
    - run: julia --project src/validation.jl
